# These are supported funding model platforms

github: [calchiwo]
patreon: # Replace with a single Patreon username
open_collective: calchiwo
ko_fi: # Replace with a single Ko-fi username
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay username
issuehunt: # Replace with a single IssueHunt username
lfx_crowdfunding: # Replace with a single LFX Crowdfunding project-name e.g., cloud-foundry
polar:
buy_me_a_coffee: calchiwo
thanks_dev: # Replace with a single thanks.dev username
custom: ["htts://buymeacofee.com/calchiwo"]
