from omnicoreagent import OmniCoreAgent
from explain_this_repo.tools import create_tools
from explain_this_repo.prompts import SYSTEM_INSTRUCTION, SECURITY_PROMPT, PERFORMANCE_PROMPT, STYLE_PROMPT
from explain_this_repo.config import AgentConfig, DEPTH_CONFIGS
import asyncio
import uuid

def create_agent(config: AgentConfig) -> OmniCoreAgent:
    """Create the single unified agent."""
    
    depth_config = DEPTH_CONFIGS.get(config.depth, DEPTH_CONFIGS["standard"])
    model_config = {"provider": config.provider, "model": config.model}
    agent_config = {
        "max_steps": depth_config["max_steps"],
        "context_management": depth_config["context_management"],
        "tool_offload": depth_config["tool_offload"],
        "memory_tool_backend": depth_config["memory_tool_backend"]
    }
    
    tools = create_tools()
    
    agent = OmniCoreAgent(
        name="explain_repo_agent",
        system_instruction=SYSTEM_INSTRUCTION,
        model_config=model_config,
        local_tools=tools,
        agent_config=agent_config,
        debug=config.debug
    )
    
    return agent


async def run_explanation(repo: str, config: AgentConfig) -> tuple[str, OmniCoreAgent, str]:
    """Run the explanation agent and return the result + the agent instance + session_id."""
    if "/" not in repo:
        raise ValueError("Repo must be in owner/repo format")
        
    owner, repo_name = repo.split("/")
    
    print(f"🚀 Starting analysis for {owner}/{repo_name}...")
    if config.verbose:
        print(f"🤖 Agent: {config.model} ({config.depth} mode)")
    
    agent = create_agent(config)
    session_id = str(uuid.uuid4())
    
    prompt = f"Analyze {owner}/{repo_name}. Generate EXPLAIN.md with an architecture diagram."
    
    # Pass session_id to maintain context
    result = await agent.run(prompt, session_id=session_id)
    
    # Return text, agent, and session_id
    return result["response"], agent, session_id



async def run_council(repo: str, config: AgentConfig) -> str:
    """
    Run the Council of Agents to audit the repository.
    Returns the compiled AUDIT.md content.
    """
    owner, repo_name = repo.split("/")
    print(f"⚖️  Summoning The Council for {owner}/{repo_name}...")

    tools = create_tools()
    
    # Common model config
    model_config = {"provider": config.provider, "model": config.model}
    
    depth_config = DEPTH_CONFIGS.get(config.depth, DEPTH_CONFIGS["standard"])
    agent_config = {
        "max_steps": depth_config["max_steps"],
        "context_management": depth_config["context_management"],
        "tool_offload": depth_config["tool_offload"],
        "memory_tool_backend": depth_config["memory_tool_backend"]
    }
    
    # Create the Specialists
    security_agent = OmniCoreAgent(
        name="security_auditor",
        system_instruction=SECURITY_PROMPT,
        model_config=model_config,
        local_tools=tools,
        agent_config=agent_config,
        debug=config.debug
    )
    
    perf_agent = OmniCoreAgent(
        name="performance_optimizer",
        system_instruction=PERFORMANCE_PROMPT,
        model_config=model_config,
        local_tools=tools,
        agent_config=agent_config,
        debug=config.debug
    )
    
    style_agent = OmniCoreAgent(
        name="code_critic",
        system_instruction=STYLE_PROMPT,
        model_config=model_config,
        local_tools=tools,
        agent_config=agent_config,
        debug=config.debug
    )

    # Context Prompt
    # We give them a specific mission based on the repo
    mission = f"Audit the repository {owner}/{repo_name}. Use your tools to inspect the code. Be harsh but fair."

    print("🕵️  Council is investigating...")
    
    # Run in parallel! This is the power of async agents.
    results = await asyncio.gather(
        security_agent.run(mission),
        perf_agent.run(mission),
        style_agent.run(mission)
    )
    
    # Aggregate results
    sec_report = results[0]["response"]
    perf_report = results[1]["response"]
    style_report = results[2]["response"]
    
    # Compile Final Report
    final_report = f"""# 🏛️ Repository Council Audit: {owner}/{repo_name}

> "The Code Has Been Judged."

{sec_report}

---

{perf_report}

---

{style_report}

---
*Generated by ExplainThisRepo Council Mode*
"""
    
    return final_report


